POST http://localhost:4000/api/student/admission/apply 
Content-Type: application/json

{
    "name": "Jojit",
    "address": "Mallikasseril (H) Kochara P.O. Manthippar",
    "email": "jojitthomas.info@gmail.com",
    "contact": "9947337790",
    "totalMark": "81",
    "admissionPreference": [
        {
            "preference": 1,
            "collegeId": "HADUK",
            "course": "B.Tech"
        },
        {
            "preference": 2,  
            "collegeId": "LAKEUK",
            "course": "B.Arch"
        },
        {
            "preference": 3,
            "collegeId": "HADUK",
            "course": "B.Tech"
        }
    ],
    "gender": "MALE",
    "markListLink": "http://s3bucket.com/tempeuniversity",
    "educationalQualification": "HighSchool",
    "DOB": "2006-01-17",
    "password": "asdfasdf"
}

###

POST http://localhost:4000/api/student/add
Content-Type: application/json

{
  "name" : "jojit thomas",
  "email" : "jojitthomas@gmail.com",
  "phone" : "9900000000",
  "address" : "mallikasseril (H) Kochara P.O. Manthippara",
  "gender" : "MALE",
  "password" : "asdfasdf",
  "batch" : "2022",
  "DOB": "10/10/2020",
  "isBlocked" : false,
  "attendence" : [{"date" : "10/10/2020", "subject" : "chemistry", "isPresent" : true}]
}

###

POST http://localhost:4000/api/auth/university/login
Content-Type: application/json

{
  "email" : "university@gmail.com",
  "password" : "university"
}


### 

GET http://localhost:4000/api/student/all

###
PATCH  http://localhost:4000/api/student/jojit@gmail.com/block

###

GET http://localhost:4000/api/student/jojit@gmail.com

###

POST http://localhost:4000/api/auth/student/login
Content-Type: application/json

{
  "email" : "jojit@gmail.com",
  "password" : "asdfasdf"
}

###

POST http://localhost:4000/api/college/apply
Content-Type: application/json

{
  "name" : "Lakedown College",
  "collegeId" : "LAKEUK",
  "place" : "United Kingdom",
  "password" : "asdfasdf",
  "university" : "507f1f77bcf86cd799439011",
  "course" : [
    {"ref" : "B.Arch", "maxCandidate" : 30}
  ]
}
###

POST http://localhost:4000/api/teacher/apply
Content-Type: application/json

{
    "name": "Christopher Joseph",
    "address": "alarivattom  P.O. Ernakulam",
    "email": "christopher@gmail.com",
    "contact": "9900000000",
    "totalMark": "81",
    "collegeId": "HADUK",
    "subject": "B.Tech",
    "gender": "MALE",
    "markListLink": "http://s3bucket.com/tempeuniversity  ",
    "qualification": "HighSchool",
    "DOB": "2022-12-12T07:16:56.143Z",
    "password": "asdfasdf",
    "skills": "Code,Speak",
    "experience": "0-6 Months"
}

###

POST http://localhost:4000/api/university/subject/add 
Content-Type: application/json

{
  "name" : "B.Tech"
}

###

GET http://localhost:4000/api/university/
Authorization: eyJhbGciOiJIUzI1NiIsIn5cCI6IkpXVCJ9.eyJpYXQiOjE2NzA2OTU1ODcsImV4cCI6MTY3MDc4MTk4N30.h6XG9MCSQqx1cFfJ5jTwMD0L9BKZvz5SQ36LeBBA26o

###

GET http://localhost:4000/api/college/list

###

PATCH  http://localhost:4000/api/college/approval/invert 
Content-Type: application/json  

{
  "collegeId" : "LAKEUK"
}

###
POST http://localhost:4000/api/student/admission/pay