POST http://localhost:4000/api/admission/apply 
Content-Type: application/json

{
  "name" : "jojit",
  "email" : "jojit@gmail.com",
  "address" : "mallikasseril (H) Kochara P.O. Manthippara",
  "gender" : "MALE",
  "totalMark" : 50,
  "markListLink" : "http://s3bucketlink",
  "admissionPreference" : [{"college" : "507f191e810c19729de860ea","course" : "507f191e810c19729de860ea" }]
}

###

POST http://localhost:4000/api/college/student/add
Content-Type: application/json

{
  "name" : "jojit",
  "email" : "jojit@gmail.com",
  "address" : "mallikasseril (H) Kochara P.O. Manthippara",
  "gender" : "MALE",
  
}

###

POST http://localhost:4000/api/auth/university/login
Content-Type: application/json

{
  "email" : "university@gmail.com",
  "password" : "university"
}